# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mark West
email: markewest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Creative, tech-savvy senior level product leader with 12+ years of 
  expertise adapting to the needs of enterprises and startups alike to deliver 
  team leadership and product success. Masterfully identifies customer pain points 
  and market needs to create design-focused products that delight customers, drive 
  value for companies and keep ahead of the market. Highly motivated and adaptable 
  self-starter with the ability to influence stakeholders, motivate engineering teams, 
  and collaborate cross-functionally to deliver on strategies. 
twitter_username: afewreMarks
github_username: afewremarks
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mark West"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Product Manager | Enterprise SaaS Product Leader & Business Development"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://markewest.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/afewremarks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afewremarks"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/afewremarks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afewremarks"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/afewremarks"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
